server:
  port: 8081
spring:
  application:
    name: iot-driver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.200.189.184:3306/iot?serverTimezone=CTT&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 60
      minimum-idle: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://101.200.189.184:9990/eureka/
#      defaultZone: http://localhost:9990/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 101.200.189.184
    non-secure-port: ${server.port}
    hostname: ${eureka.instance.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}

mybatis:
  mapper-locations: classpath:mapperImpl/*Mapper.xml

mqtt:
  host: tcp://101.200.189.184:1883
  userName: test
  password: test
  pubClientId: pubClient1
  subClientId: subClient1

ribbon:
  ConnectTimeout: 10000 # ribbon链接超时时长
  ReadTimeout: 10000 # ribbon读取超时时间长