server:
  port: 8081
spring:
  application:
    name: iot-driver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.200.189.184:3306/iotTest?serverTimezone=CTT&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 60
      minimum-idle: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
eureka:
  client:
    serviceUrl:
#      defaultZone: http://123.56.253.41:9990/eureka/
      defaultZone: http://localhost:9990/eureka/
  instance:
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapperImpl/*Mapper.xml

mqtt:
  host: tcp://101.200.189.184:1883
  userName: test
  password: test
  pubClientId: pubClient
  subClientId: subClient