

server:
  port: 8083
spring:
  application:
    name: iot-data
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.55.92.12:3306/iot?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://123.56.253.41:9990/eureka/
  instance:
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:data/*.xml