
server:
  port: 8080
spring:
  application:
    name: iot-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iot
    username: iot
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: localhost
    port: 6379
#    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://101.200.189.184:9990/eureka/
  instance:
    prefer-ip-address: true