
server:
  port: 8100
spring:
  application:
    name: iot-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ismzl.com:3306/iot?useUnicode=true&characterEncoding=UTF-8
    username: iot
    password: iot123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: localhost
    port: 6379
#    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://123.56.253.41:9990/eureka/
  instance:
    prefer-ip-address: true